//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteApi2.ReferenciaServicioJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ModeloServicio/", ConfigurationName="ReferenciaServicioJava.Servicios")]
    public interface Servicios {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarLaboratorioRequest", ReplyAction="http://ModeloServicio/Servicios/listarLaboratorioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.listarLaboratorioResponse listarLaboratorio(ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarLaboratorioRequest", ReplyAction="http://ModeloServicio/Servicios/listarLaboratorioResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarLaboratorioResponse> listarLaboratorioAsync(ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarMedicamentosRequest", ReplyAction="http://ModeloServicio/Servicios/listarMedicamentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.listarMedicamentosResponse listarMedicamentos(ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarMedicamentosRequest", ReplyAction="http://ModeloServicio/Servicios/listarMedicamentosResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarMedicamentosResponse> listarMedicamentosAsync(ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarcodigoRequest", ReplyAction="http://ModeloServicio/Servicios/listarcodigoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.listarcodigoResponse listarcodigo(ClienteApi2.ReferenciaServicioJava.listarcodigoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarcodigoRequest", ReplyAction="http://ModeloServicio/Servicios/listarcodigoResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarcodigoResponse> listarcodigoAsync(ClienteApi2.ReferenciaServicioJava.listarcodigoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarNombreRequest", ReplyAction="http://ModeloServicio/Servicios/listarNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.listarNombreResponse listarNombre(ClienteApi2.ReferenciaServicioJava.listarNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/listarNombreRequest", ReplyAction="http://ModeloServicio/Servicios/listarNombreResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarNombreResponse> listarNombreAsync(ClienteApi2.ReferenciaServicioJava.listarNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/EliminarRequest", ReplyAction="http://ModeloServicio/Servicios/EliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.EliminarResponse Eliminar(ClienteApi2.ReferenciaServicioJava.EliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/EliminarRequest", ReplyAction="http://ModeloServicio/Servicios/EliminarResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.EliminarResponse> EliminarAsync(ClienteApi2.ReferenciaServicioJava.EliminarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/insertarArchivoRequest", ReplyAction="http://ModeloServicio/Servicios/insertarArchivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.insertarArchivoResponse insertarArchivo(ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/insertarArchivoRequest", ReplyAction="http://ModeloServicio/Servicios/insertarArchivoResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.insertarArchivoResponse> insertarArchivoAsync(ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/ventaActualizarRequest", ReplyAction="http://ModeloServicio/Servicios/ventaActualizarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.ventaActualizarResponse ventaActualizar(ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/ventaActualizarRequest", ReplyAction="http://ModeloServicio/Servicios/ventaActualizarResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.ventaActualizarResponse> ventaActualizarAsync(ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/agregarRequest", ReplyAction="http://ModeloServicio/Servicios/agregarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.agregarResponse agregar(ClienteApi2.ReferenciaServicioJava.agregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/agregarRequest", ReplyAction="http://ModeloServicio/Servicios/agregarResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.agregarResponse> agregarAsync(ClienteApi2.ReferenciaServicioJava.agregarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/ActualizarRequest", ReplyAction="http://ModeloServicio/Servicios/ActualizarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteApi2.ReferenciaServicioJava.ActualizarResponse Actualizar(ClienteApi2.ReferenciaServicioJava.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ModeloServicio/Servicios/ActualizarRequest", ReplyAction="http://ModeloServicio/Servicios/ActualizarResponse")]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.ActualizarResponse> ActualizarAsync(ClienteApi2.ReferenciaServicioJava.ActualizarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ModeloServicio/")]
    public partial class medicamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidad_existenciaField;
        
        private int codigoField;
        
        private string dosisField;
        
        private string laboratorio_farmaceuticoField;
        
        private string medicamento1Field;
        
        private double precio_unitarioField;
        
        private string presentacionField;
        
        private string vencimientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad_existencia {
            get {
                return this.cantidad_existenciaField;
            }
            set {
                this.cantidad_existenciaField = value;
                this.RaisePropertyChanged("cantidad_existencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dosis {
            get {
                return this.dosisField;
            }
            set {
                this.dosisField = value;
                this.RaisePropertyChanged("dosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string laboratorio_farmaceutico {
            get {
                return this.laboratorio_farmaceuticoField;
            }
            set {
                this.laboratorio_farmaceuticoField = value;
                this.RaisePropertyChanged("laboratorio_farmaceutico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("medicamento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string medicamento1 {
            get {
                return this.medicamento1Field;
            }
            set {
                this.medicamento1Field = value;
                this.RaisePropertyChanged("medicamento1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precio_unitario {
            get {
                return this.precio_unitarioField;
            }
            set {
                this.precio_unitarioField = value;
                this.RaisePropertyChanged("precio_unitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string presentacion {
            get {
                return this.presentacionField;
            }
            set {
                this.presentacionField = value;
                this.RaisePropertyChanged("presentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string vencimiento {
            get {
                return this.vencimientoField;
            }
            set {
                this.vencimientoField = value;
                this.RaisePropertyChanged("vencimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLaboratorio", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarLaboratorioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LaboratorioFarmaceutico;
        
        public listarLaboratorioRequest() {
        }
        
        public listarLaboratorioRequest(string LaboratorioFarmaceutico) {
            this.LaboratorioFarmaceutico = LaboratorioFarmaceutico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLaboratorioResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarLaboratorioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteApi2.ReferenciaServicioJava.medicamento[] @return;
        
        public listarLaboratorioResponse() {
        }
        
        public listarLaboratorioResponse(ClienteApi2.ReferenciaServicioJava.medicamento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMedicamentos", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarMedicamentosRequest {
        
        public listarMedicamentosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMedicamentosResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarMedicamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteApi2.ReferenciaServicioJava.medicamento[] @return;
        
        public listarMedicamentosResponse() {
        }
        
        public listarMedicamentosResponse(ClienteApi2.ReferenciaServicioJava.medicamento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarcodigo", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarcodigoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Codigo;
        
        public listarcodigoRequest() {
        }
        
        public listarcodigoRequest(int Codigo) {
            this.Codigo = Codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarcodigoResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarcodigoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteApi2.ReferenciaServicioJava.medicamento @return;
        
        public listarcodigoResponse() {
        }
        
        public listarcodigoResponse(ClienteApi2.ReferenciaServicioJava.medicamento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarNombre", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreMedicamento;
        
        public listarNombreRequest() {
        }
        
        public listarNombreRequest(string nombreMedicamento) {
            this.nombreMedicamento = nombreMedicamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarNombreResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class listarNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteApi2.ReferenciaServicioJava.medicamento[] @return;
        
        public listarNombreResponse() {
        }
        
        public listarNombreResponse(ClienteApi2.ReferenciaServicioJava.medicamento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class EliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Codigo;
        
        public EliminarRequest() {
        }
        
        public EliminarRequest(int Codigo) {
            this.Codigo = Codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class EliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteApi2.ReferenciaServicioJava.medicamento @return;
        
        public EliminarResponse() {
        }
        
        public EliminarResponse(ClienteApi2.ReferenciaServicioJava.medicamento @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArchivo", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class insertarArchivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rutaArchivo;
        
        public insertarArchivoRequest() {
        }
        
        public insertarArchivoRequest(string rutaArchivo) {
            this.rutaArchivo = rutaArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArchivoResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class insertarArchivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarArchivoResponse() {
        }
        
        public insertarArchivoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ventaActualizar", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class ventaActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Cantidad;
        
        public ventaActualizarRequest() {
        }
        
        public ventaActualizarRequest(int Codigo, int Cantidad) {
            this.Codigo = Codigo;
            this.Cantidad = Cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ventaActualizarResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class ventaActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public ventaActualizarResponse() {
        }
        
        public ventaActualizarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregar", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class agregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Medicamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dosis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Precio_unitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Cantidad_existencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Laboratorio_farmaceutico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Presentacion;
        
        public agregarRequest() {
        }
        
        public agregarRequest(string Medicamento, string Dosis, double Precio_unitario, int Cantidad_existencia, string Laboratorio_farmaceutico, string Vencimiento, string Presentacion) {
            this.Medicamento = Medicamento;
            this.Dosis = Dosis;
            this.Precio_unitario = Precio_unitario;
            this.Cantidad_existencia = Cantidad_existencia;
            this.Laboratorio_farmaceutico = Laboratorio_farmaceutico;
            this.Vencimiento = Vencimiento;
            this.Presentacion = Presentacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class agregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public agregarResponse() {
        }
        
        public agregarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Actualizar", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class ActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Medicamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dosis;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Precio_unitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Cantidad_existencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Laboratorio_farmaceutico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vencimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Presentacion;
        
        public ActualizarRequest() {
        }
        
        public ActualizarRequest(int Codigo, string Medicamento, string Dosis, double Precio_unitario, int Cantidad_existencia, string Laboratorio_farmaceutico, string Vencimiento, string Presentacion) {
            this.Codigo = Codigo;
            this.Medicamento = Medicamento;
            this.Dosis = Dosis;
            this.Precio_unitario = Precio_unitario;
            this.Cantidad_existencia = Cantidad_existencia;
            this.Laboratorio_farmaceutico = Laboratorio_farmaceutico;
            this.Vencimiento = Vencimiento;
            this.Presentacion = Presentacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarResponse", WrapperNamespace="http://ModeloServicio/", IsWrapped=true)]
    public partial class ActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ModeloServicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ActualizarResponse() {
        }
        
        public ActualizarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosChannel : ClienteApi2.ReferenciaServicioJava.Servicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<ClienteApi2.ReferenciaServicioJava.Servicios>, ClienteApi2.ReferenciaServicioJava.Servicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.listarLaboratorioResponse ClienteApi2.ReferenciaServicioJava.Servicios.listarLaboratorio(ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest request) {
            return base.Channel.listarLaboratorio(request);
        }
        
        public ClienteApi2.ReferenciaServicioJava.medicamento[] listarLaboratorio(string LaboratorioFarmaceutico) {
            ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest();
            inValue.LaboratorioFarmaceutico = LaboratorioFarmaceutico;
            ClienteApi2.ReferenciaServicioJava.listarLaboratorioResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarLaboratorio(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarLaboratorioResponse> ClienteApi2.ReferenciaServicioJava.Servicios.listarLaboratorioAsync(ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest request) {
            return base.Channel.listarLaboratorioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarLaboratorioResponse> listarLaboratorioAsync(string LaboratorioFarmaceutico) {
            ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarLaboratorioRequest();
            inValue.LaboratorioFarmaceutico = LaboratorioFarmaceutico;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarLaboratorioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.listarMedicamentosResponse ClienteApi2.ReferenciaServicioJava.Servicios.listarMedicamentos(ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest request) {
            return base.Channel.listarMedicamentos(request);
        }
        
        public ClienteApi2.ReferenciaServicioJava.medicamento[] listarMedicamentos() {
            ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest();
            ClienteApi2.ReferenciaServicioJava.listarMedicamentosResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarMedicamentos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarMedicamentosResponse> ClienteApi2.ReferenciaServicioJava.Servicios.listarMedicamentosAsync(ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest request) {
            return base.Channel.listarMedicamentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarMedicamentosResponse> listarMedicamentosAsync() {
            ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarMedicamentosRequest();
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarMedicamentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.listarcodigoResponse ClienteApi2.ReferenciaServicioJava.Servicios.listarcodigo(ClienteApi2.ReferenciaServicioJava.listarcodigoRequest request) {
            return base.Channel.listarcodigo(request);
        }
        
        public ClienteApi2.ReferenciaServicioJava.medicamento listarcodigo(int Codigo) {
            ClienteApi2.ReferenciaServicioJava.listarcodigoRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarcodigoRequest();
            inValue.Codigo = Codigo;
            ClienteApi2.ReferenciaServicioJava.listarcodigoResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarcodigo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarcodigoResponse> ClienteApi2.ReferenciaServicioJava.Servicios.listarcodigoAsync(ClienteApi2.ReferenciaServicioJava.listarcodigoRequest request) {
            return base.Channel.listarcodigoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarcodigoResponse> listarcodigoAsync(int Codigo) {
            ClienteApi2.ReferenciaServicioJava.listarcodigoRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarcodigoRequest();
            inValue.Codigo = Codigo;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarcodigoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.listarNombreResponse ClienteApi2.ReferenciaServicioJava.Servicios.listarNombre(ClienteApi2.ReferenciaServicioJava.listarNombreRequest request) {
            return base.Channel.listarNombre(request);
        }
        
        public ClienteApi2.ReferenciaServicioJava.medicamento[] listarNombre(string nombreMedicamento) {
            ClienteApi2.ReferenciaServicioJava.listarNombreRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarNombreRequest();
            inValue.nombreMedicamento = nombreMedicamento;
            ClienteApi2.ReferenciaServicioJava.listarNombreResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarNombreResponse> ClienteApi2.ReferenciaServicioJava.Servicios.listarNombreAsync(ClienteApi2.ReferenciaServicioJava.listarNombreRequest request) {
            return base.Channel.listarNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.listarNombreResponse> listarNombreAsync(string nombreMedicamento) {
            ClienteApi2.ReferenciaServicioJava.listarNombreRequest inValue = new ClienteApi2.ReferenciaServicioJava.listarNombreRequest();
            inValue.nombreMedicamento = nombreMedicamento;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).listarNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.EliminarResponse ClienteApi2.ReferenciaServicioJava.Servicios.Eliminar(ClienteApi2.ReferenciaServicioJava.EliminarRequest request) {
            return base.Channel.Eliminar(request);
        }
        
        public ClienteApi2.ReferenciaServicioJava.medicamento Eliminar(int Codigo) {
            ClienteApi2.ReferenciaServicioJava.EliminarRequest inValue = new ClienteApi2.ReferenciaServicioJava.EliminarRequest();
            inValue.Codigo = Codigo;
            ClienteApi2.ReferenciaServicioJava.EliminarResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).Eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.EliminarResponse> ClienteApi2.ReferenciaServicioJava.Servicios.EliminarAsync(ClienteApi2.ReferenciaServicioJava.EliminarRequest request) {
            return base.Channel.EliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.EliminarResponse> EliminarAsync(int Codigo) {
            ClienteApi2.ReferenciaServicioJava.EliminarRequest inValue = new ClienteApi2.ReferenciaServicioJava.EliminarRequest();
            inValue.Codigo = Codigo;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).EliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.insertarArchivoResponse ClienteApi2.ReferenciaServicioJava.Servicios.insertarArchivo(ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest request) {
            return base.Channel.insertarArchivo(request);
        }
        
        public int insertarArchivo(string rutaArchivo) {
            ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest inValue = new ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest();
            inValue.rutaArchivo = rutaArchivo;
            ClienteApi2.ReferenciaServicioJava.insertarArchivoResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).insertarArchivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.insertarArchivoResponse> ClienteApi2.ReferenciaServicioJava.Servicios.insertarArchivoAsync(ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest request) {
            return base.Channel.insertarArchivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.insertarArchivoResponse> insertarArchivoAsync(string rutaArchivo) {
            ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest inValue = new ClienteApi2.ReferenciaServicioJava.insertarArchivoRequest();
            inValue.rutaArchivo = rutaArchivo;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).insertarArchivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.ventaActualizarResponse ClienteApi2.ReferenciaServicioJava.Servicios.ventaActualizar(ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest request) {
            return base.Channel.ventaActualizar(request);
        }
        
        public int ventaActualizar(int Codigo, int Cantidad) {
            ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest inValue = new ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest();
            inValue.Codigo = Codigo;
            inValue.Cantidad = Cantidad;
            ClienteApi2.ReferenciaServicioJava.ventaActualizarResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).ventaActualizar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.ventaActualizarResponse> ClienteApi2.ReferenciaServicioJava.Servicios.ventaActualizarAsync(ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest request) {
            return base.Channel.ventaActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.ventaActualizarResponse> ventaActualizarAsync(int Codigo, int Cantidad) {
            ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest inValue = new ClienteApi2.ReferenciaServicioJava.ventaActualizarRequest();
            inValue.Codigo = Codigo;
            inValue.Cantidad = Cantidad;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).ventaActualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.agregarResponse ClienteApi2.ReferenciaServicioJava.Servicios.agregar(ClienteApi2.ReferenciaServicioJava.agregarRequest request) {
            return base.Channel.agregar(request);
        }
        
        public string agregar(string Medicamento, string Dosis, double Precio_unitario, int Cantidad_existencia, string Laboratorio_farmaceutico, string Vencimiento, string Presentacion) {
            ClienteApi2.ReferenciaServicioJava.agregarRequest inValue = new ClienteApi2.ReferenciaServicioJava.agregarRequest();
            inValue.Medicamento = Medicamento;
            inValue.Dosis = Dosis;
            inValue.Precio_unitario = Precio_unitario;
            inValue.Cantidad_existencia = Cantidad_existencia;
            inValue.Laboratorio_farmaceutico = Laboratorio_farmaceutico;
            inValue.Vencimiento = Vencimiento;
            inValue.Presentacion = Presentacion;
            ClienteApi2.ReferenciaServicioJava.agregarResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).agregar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.agregarResponse> ClienteApi2.ReferenciaServicioJava.Servicios.agregarAsync(ClienteApi2.ReferenciaServicioJava.agregarRequest request) {
            return base.Channel.agregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.agregarResponse> agregarAsync(string Medicamento, string Dosis, double Precio_unitario, int Cantidad_existencia, string Laboratorio_farmaceutico, string Vencimiento, string Presentacion) {
            ClienteApi2.ReferenciaServicioJava.agregarRequest inValue = new ClienteApi2.ReferenciaServicioJava.agregarRequest();
            inValue.Medicamento = Medicamento;
            inValue.Dosis = Dosis;
            inValue.Precio_unitario = Precio_unitario;
            inValue.Cantidad_existencia = Cantidad_existencia;
            inValue.Laboratorio_farmaceutico = Laboratorio_farmaceutico;
            inValue.Vencimiento = Vencimiento;
            inValue.Presentacion = Presentacion;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).agregarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteApi2.ReferenciaServicioJava.ActualizarResponse ClienteApi2.ReferenciaServicioJava.Servicios.Actualizar(ClienteApi2.ReferenciaServicioJava.ActualizarRequest request) {
            return base.Channel.Actualizar(request);
        }
        
        public string Actualizar(int Codigo, string Medicamento, string Dosis, double Precio_unitario, int Cantidad_existencia, string Laboratorio_farmaceutico, string Vencimiento, string Presentacion) {
            ClienteApi2.ReferenciaServicioJava.ActualizarRequest inValue = new ClienteApi2.ReferenciaServicioJava.ActualizarRequest();
            inValue.Codigo = Codigo;
            inValue.Medicamento = Medicamento;
            inValue.Dosis = Dosis;
            inValue.Precio_unitario = Precio_unitario;
            inValue.Cantidad_existencia = Cantidad_existencia;
            inValue.Laboratorio_farmaceutico = Laboratorio_farmaceutico;
            inValue.Vencimiento = Vencimiento;
            inValue.Presentacion = Presentacion;
            ClienteApi2.ReferenciaServicioJava.ActualizarResponse retVal = ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).Actualizar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.ActualizarResponse> ClienteApi2.ReferenciaServicioJava.Servicios.ActualizarAsync(ClienteApi2.ReferenciaServicioJava.ActualizarRequest request) {
            return base.Channel.ActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteApi2.ReferenciaServicioJava.ActualizarResponse> ActualizarAsync(int Codigo, string Medicamento, string Dosis, double Precio_unitario, int Cantidad_existencia, string Laboratorio_farmaceutico, string Vencimiento, string Presentacion) {
            ClienteApi2.ReferenciaServicioJava.ActualizarRequest inValue = new ClienteApi2.ReferenciaServicioJava.ActualizarRequest();
            inValue.Codigo = Codigo;
            inValue.Medicamento = Medicamento;
            inValue.Dosis = Dosis;
            inValue.Precio_unitario = Precio_unitario;
            inValue.Cantidad_existencia = Cantidad_existencia;
            inValue.Laboratorio_farmaceutico = Laboratorio_farmaceutico;
            inValue.Vencimiento = Vencimiento;
            inValue.Presentacion = Presentacion;
            return ((ClienteApi2.ReferenciaServicioJava.Servicios)(this)).ActualizarAsync(inValue);
        }
    }
}
